package View;

import DAO.ProdutoDAO;
import Model.Produto;
import Result.Resultado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GerenciaProduto extends javax.swing.JFrame {

    private final ProdutoDAO produtoDAO;
    private ArrayList<Produto> listaProdutos;
    private final boolean possuiAdmin;
    private final boolean visualizaEmFalta;
    private final static SimpleDateFormat formataDataInicial = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    private final static SimpleDateFormat formataDataFinal = new SimpleDateFormat("dd/MM/yyyy");
    private final DecimalFormat formataMoeda = new DecimalFormat("R$ #,##0.00");
    
    public GerenciaProduto(boolean possuiAdmin, boolean visualizaEmFalta) {
        initComponents();
        this.produtoDAO = new ProdutoDAO();
        this.possuiAdmin = possuiAdmin;
        this.visualizaEmFalta = visualizaEmFalta;
        this.carregarTabela();
        this.carregarInformacoes();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ArrayList<String> categorias = this.produtoDAO.getListaCategorias();
        for (int i = 0; i < categorias.size(); i++) {
            filtro.addItem(categorias.get(i));
        }
        
        // Adicionar ActionListener para detectar mudanças de seleção
        filtro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Ação a ser executada quando a seleção muda
                String categoriaSelecionada = (String) filtro.getSelectedItem();
                System.out.println("Categoria selecionada: " + categoriaSelecionada);
                GerenciaProduto.this.carregarTabela(categoriaSelecionada);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_visualizar = new javax.swing.JButton();
        b_apagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jTitulo = new javax.swing.JLabel();
        filtro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estoque de Produtos - Null Alliance");

        b_visualizar.setText("Visualizar");
        b_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_visualizarActionPerformed(evt);
            }
        });

        b_apagar.setText("Apagar");
        b_apagar.setEnabled(false);
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cód. Produto", "Nome", "Descrição", "Qnt. Estoque", "Preço", "Categoria", "Data Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        jTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("Estoque");

        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NENHUM" }));

        jLabel1.setText("Filtrar por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_visualizar)
                        .addGap(18, 18, 18)
                        .addComponent(b_apagar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                            .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_visualizar)
                    .addComponent(b_apagar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_visualizarActionPerformed
        try {
            if (this.jTableProdutos.getSelectedRow() == -1) {
                throw new Exception("Primeiro selecione um produto para visualizar.");
            } else {
                Produto produtoSelecionado = pegarDadosProdutoSelecionado();
                new VisualizaProduto(produtoSelecionado, possuiAdmin, visualizaEmFalta).setVisible(true);
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            carregarTabela();
            carregarInformacoes();
        }
    }//GEN-LAST:event_b_visualizarActionPerformed

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
        try {
            int id = 0;
            if (this.jTableProdutos.getSelectedRow() == -1) {
                throw new Exception("Primeiro selecione um produto para apagar.");
            } else {
                id = Integer.parseInt(this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
            }

            int respostaProduto = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar este produto?");

            if (respostaProduto == 0) {
                Resultado resultado = this.produtoDAO.deletarProduto(id);
                JOptionPane.showMessageDialog(rootPane, resultado.getMensagem());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            carregarTabela();
            carregarInformacoes();
        }
    }//GEN-LAST:event_b_apagarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked

    }//GEN-LAST:event_jTableProdutosMouseClicked

    @SuppressWarnings("unchecked")
    public final void carregarTabela() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) this.jTableProdutos.getModel();
            modelo.setNumRows(0);
            if (visualizaEmFalta) {
                this.listaProdutos = this.produtoDAO.getProdutosEmFalta();
            } else {
                this.listaProdutos = this.produtoDAO.getListaProdutos();
            }

            for (Produto produto : listaProdutos) {
                String data = formataDataFinal.format(formataDataInicial.parse(produto.getDataCadastro()));
                String preco = formataMoeda.format(produto.getPreco());

                modelo.addRow(new Object[]{
                    produto.getCodigoProduto(),
                    produto.getNomeProduto(),
                    produto.getDescricaoProduto(),
                    produto.getQuantidadeEstoque(),
                    preco,
                    produto.getCategoria(),
                    data,
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public final void carregarTabela(String categoria) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) this.jTableProdutos.getModel();
            modelo.setNumRows(0);
            if (visualizaEmFalta) {
                this.listaProdutos = this.produtoDAO.getProdutosEmFalta();
            } else {
                if (categoria != "") {
                    this.listaProdutos = this.produtoDAO.getListaProdutos(categoria);
                } else {
                    this.listaProdutos = this.produtoDAO.getListaProdutos();
                }
            }

            for (Produto produto : listaProdutos) {
                String data = formataDataFinal.format(formataDataInicial.parse(produto.getDataCadastro()));
                String preco = formataMoeda.format(produto.getPreco());

                modelo.addRow(new Object[]{
                    produto.getCodigoProduto(),
                    produto.getNomeProduto(),
                    produto.getDescricaoProduto(),
                    produto.getQuantidadeEstoque(),
                    preco,
                    produto.getCategoria(),
                    data,
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void carregarInformacoes() {
        this.jTitulo.setText(construirTitulo());
        this.b_apagar.setEnabled(possuiAdmin);
    }
    
    private Produto pegarDadosProdutoSelecionado() {
        int codigoProduto = Integer.parseInt(this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
        return produtoDAO.carregarProduto(codigoProduto);
    }
    
    private String construirTitulo() {
        String sufixoProduto;
        int tamanhoLista = listaProdutos.size();
        if (tamanhoLista != 1) { 
            sufixoProduto = "s";
        } else {
            sufixoProduto = "";
        }
        if (visualizaEmFalta) {
            return ("Estoque - " + tamanhoLista + " produto" + sufixoProduto + " em falta");
        } else {
            return ("Estoque - " + tamanhoLista + " produto" + sufixoProduto);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_apagar;
    private javax.swing.JButton b_visualizar;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
