/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ProdutoDAO;
import Model.Produto;
import Result.Resultado;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofia
 */
public class VisualizaProduto extends javax.swing.JFrame {
    
    private Produto produtoSelecionado;
    private final ProdutoDAO dao;

    /**
     * Creates new form VisualizaProduto
     * @param produto
     */
    public VisualizaProduto(Produto produto) {
        System.out.println(produto);
        this.dao = new ProdutoDAO();
        initComponents();
        this.produtoSelecionado = produto;
        this.preencherDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNomeProduto = new javax.swing.JLabel();
        jDescricaoLabel = new javax.swing.JLabel();
        jDescricaoProduto = new javax.swing.JLabel();
        jQuantidadeLabel = new javax.swing.JLabel();
        jQuantidadeProduto = new javax.swing.JLabel();
        jCodigoLabel = new javax.swing.JLabel();
        jCodigoProduto = new javax.swing.JLabel();
        jCategoriaLabel = new javax.swing.JLabel();
        jCategoriaProduto = new javax.swing.JLabel();
        jPrecoLabel = new javax.swing.JLabel();
        jPrecoProduto = new javax.swing.JLabel();
        jDataLabel = new javax.swing.JLabel();
        jDataProduto = new javax.swing.JLabel();
        b_alterar = new javax.swing.JButton();
        b_apagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jNomeProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNomeProduto.setText("jLabel1");

        jDescricaoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDescricaoLabel.setText("Descrição:");

        jDescricaoProduto.setText("jLabel1");

        jQuantidadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jQuantidadeLabel.setText("Quantidade em estoque:");

        jQuantidadeProduto.setText("jLabel1");

        jCodigoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCodigoLabel.setText("Código:");

        jCodigoProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCodigoProduto.setText("Código:");

        jCategoriaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCategoriaLabel.setText("Categoria:");

        jCategoriaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCategoriaProduto.setText("Código:");

        jPrecoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPrecoLabel.setText("Preço:");

        jPrecoProduto.setText("jLabel1");

        jDataLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDataLabel.setText("Data de cadastro:");

        jDataProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDataProduto.setText("Data de cadastro:");

        b_alterar.setText("Alterar");
        b_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarActionPerformed(evt);
            }
        });

        b_apagar.setText("Apagar");
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDataLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDataProduto))
                    .addComponent(jDescricaoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jCodigoLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jDescricaoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jQuantidadeProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jQuantidadeLabel))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCategoriaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPrecoLabel)
                            .addComponent(jPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(b_alterar)
                .addGap(18, 18, 18)
                .addComponent(b_apagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodigoLabel)
                    .addComponent(jCodigoProduto)
                    .addComponent(jCategoriaLabel)
                    .addComponent(jCategoriaProduto))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDescricaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jQuantidadeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPrecoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDataLabel)
                    .addComponent(jDataProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_alterar)
                    .addComponent(b_apagar))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed

        try {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_b_alterarActionPerformed

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
//        try {
//            int id = 0;
//            if (this.jTableProdutos.getSelectedRow() == -1) {
//                throw new Exception("Primeiro selecione um produto para apagar.");
//            } else {
//                id = Integer.parseInt(this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
//            }
//
//            int resposta_produto = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar este produto?");
//
//            if (resposta_produto == 0) {
//                Resultado resultado = this.produtoDAO.DeleteProdutoDB(id);
//                JOptionPane.showMessageDialog(rootPane, resultado.getMensagem());
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        } finally {
//            carregaTabela();
//        }
    }//GEN-LAST:event_b_apagarActionPerformed

    private void preencherDados() {
        this.jCategoriaProduto.setText(this.produtoSelecionado.getCategoria_produto());
        this.jCodigoProduto.setText(String.valueOf(this.produtoSelecionado.getCodigo_produto()));
        this.jDataProduto.setText(this.produtoSelecionado.getData_cadastro());
        this.jDescricaoProduto.setText(this.produtoSelecionado.getDescricao_produto());
        this.jNomeProduto.setText(this.produtoSelecionado.getNome_produto());
        this.jPrecoProduto.setText("R$ " + String.valueOf(this.produtoSelecionado.getPreco()));
        this.jQuantidadeProduto.setText(String.valueOf(this.produtoSelecionado.getQuantidade_estoque()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar;
    private javax.swing.JButton b_apagar;
    private javax.swing.JLabel jCategoriaLabel;
    private javax.swing.JLabel jCategoriaProduto;
    private javax.swing.JLabel jCodigoLabel;
    private javax.swing.JLabel jCodigoProduto;
    private javax.swing.JLabel jDataLabel;
    private javax.swing.JLabel jDataProduto;
    private javax.swing.JLabel jDescricaoLabel;
    private javax.swing.JLabel jDescricaoProduto;
    private javax.swing.JLabel jNomeProduto;
    private javax.swing.JLabel jPrecoLabel;
    private javax.swing.JLabel jPrecoProduto;
    private javax.swing.JLabel jQuantidadeLabel;
    private javax.swing.JLabel jQuantidadeProduto;
    // End of variables declaration//GEN-END:variables
}
